### DISCUSSION TITLE
Probleem ruuteris http.post päringul mitme taseme muutujale andmete kaasaandmisega

### DISCUSSION THREAD

**Discussion by RaulAltmae** [buerokratt/Ruuter#132] [General]
probleem ei ole mitme taseme parameetris vaid muutuja andmises sügavamale kui 1 aste ehk probleemi tekkitab ${responseName} kui see asendad "fallback" siis toimib.

```yaml
assign_values:
  assign:
    responseName: "*fallback*"
    responseText: "test"
getResponsesWithName:
  call: http.post
  args:
    url: http://host.docker.internal:9200/response/_search
    body:
      query:
        bool:
          must:
            - query_string:
                query: ${responseName}
                default_field: "name"
  result: getResponsesResult
```
![image](https://user-images.githubusercontent.com/120466882/216547010-7e45adb8-ee48-4650-9045-dd79bb7fca7a.png)
