### DISCUSSION TITLE
Ruuter mixing up responses when multiple requests in parallel using conditions

### DISCUSSION THREAD

**Discussion by gdrui** [buerokratt/Ruuter#133] [General]
Given an endpoint that fetches different data from Resql based on the provided parameters:
<details>

```
extract_request_data:
  assign:
    requestedMetric: ${incoming.params.metric}

checkMetric:
  switch:
    - condition: ${requestedMetric === 'total_chats_day'}
      next: getTotalChatsDayResults
    - condition: ${requestedMetric === 'total_chats_month'}
      next: getTotalChatsMonthResults
    - condition: ${requestedMetric === 'total_chats_no_csa_day'}
      next: getTotalChatsNoCSAResults
    - condition: ${requestedMetric === 'avg_chats_by_month'}
      next: getAvgChatsMonthResults
    - condition: ${requestedMetric === 'avg_chats_by_week'}
      next: getAvgChatsWeekResults
    - condition: ${requestedMetric === 'avg_chats_no_csa_by_month'}
      next: getAvgChatsNoCSAMonthResult
    - condition: ${requestedMetric === 'avg_chats_no_csa_by_week'}
      next: getAvgChatsNoCSAWeekResult
    - condition: ${requestedMetric === 'avg_waiting_time_day'}
      next: getAvgWaitingTimeDayResult
    - condition: ${requestedMetric === 'avg_waiting_time_week'}
      next: getAvgWaitingTimeWeekResult
    - condition: ${requestedMetric === 'total_forwarded_chats_yesterday'}
      next: getTotalForwardedChatsResult
    - condition: ${requestedMetric === 'chat-activity'}
      next: getChatActivityResult
  next: invalidMetric
```
</details>

If this endpoint is called once with any valid parameter it will return the correct result. 
However if many or all of these options are called in parallel requests then sometimes the results get mixed up and for example I can receive the result of `avg_waiting_time_day` when the request was with the parameter `total_chats_day`

I also tried to replace the individual steps so that instead of an asynchronous http.post step each step would only return a unique value like :
```
getTotalChatsDayResults:
  return: 'A'
  next: end
  
getTotalChatsMonthResults:
  return: 'B'
  next: end
...
```
This seems to happen less frequently like this, but I still observe the same thing happening:

When its OK:
<img width="498" alt="Screenshot 2023-02-03 at 11 21 18" src="https://user-images.githubusercontent.com/107122512/216561576-a8012ec7-1c12-474f-8735-f75bfefbbe6e.png">
When its not OK:
<img width="541" alt="Screenshot 2023-02-03 at 11 21 15" src="https://user-images.githubusercontent.com/107122512/216561695-23af8c42-4936-44ac-9a08-09ce7f500aa4.png">

**Comment by gdrui** [comment]
<details>
 <summary>Here is a complete Ruuter DSL</summary>

```
extract_request_data:
  assign:
    requestedMetric: ${incoming.params.metric}

checkMetric:
  switch:
    - condition: ${requestedMetric === 'a'}
      next: getA
    - condition: ${requestedMetric === 'b'}
      next: getB
    - condition: ${requestedMetric === 'c'}
      next: getC
    - condition: ${requestedMetric === 'd'}
      next: getD
    - condition: ${requestedMetric === 'e'}
      next: getE
    - condition: ${requestedMetric === 'f'}
      next: getF
    - condition: ${requestedMetric === 'g'}
      next: getG
    - condition: ${requestedMetric === 'h'}
      next: getH
    - condition: ${requestedMetric === 'i'}
      next: getI
    - condition: ${requestedMetric === 'j'}
      next: getJ
    - condition: ${requestedMetric === 'k'}
      next: getK
  next: invalidMetric

getA:
  return: 'A'
  next: end

getB:
  return: 'B'
  next: end

getC:
  return: 'C'
  next: end

getD:
  return: 'D'
  next: end

getE:
  return: 'E'
  next: end

getF:
  return: 'F'
  next: end

getG:
  return: 'G'
  next: end

getH:
  return: 'H'
  next: end

getI:
  return: 'I'
  next: end

getJ:
  return: 'J'
  next: end

getK:
  return: 'K'
  next: end

invalidMetric:
  status: 400
  return: 'invalid metric requested'
```
</details>

<details>
<summary>Here is a sample index.html that will call this endpoint and count failed requests</summary>

```
<script>
  const metrics = 'abcdefghijk';

  let issueCount = 0;
  let passCount = 0;

  const getAllMetrics = async () => {
    const promises = [...metrics].map((m) =>
      fetch(`http://localhost:8080/overview/metrics?metric=${m}`).then((r) =>
        r.json()
      )
    );
    const results = await Promise.all(promises);
    checkResults(results);
  };

  const checkResults = (results) => {
    results.forEach((r, i) => {
      if (r.response === metrics[i].toUpperCase()) {
        passCount++;
      } else {
        issueCount++;
      }
    });
    document.open();
    document.write(
      `<h3>Good requests: ${passCount}</h3><h3>Bad requests: ${issueCount}</h3>`
    );
    document.close();
  };

  setInterval(() => getAllMetrics(), 1000);
</script>

```
</details>

As long as Ruuter is set up to accept CORS from http://localhost:3000, you can serve this index.html with 
`npx http-server -p 3000 -o -a localhost` in the same folder where the index.html file is.

After keeping the tab open for a little while, this is the result:

<img width="276" alt="Screenshot 2023-02-03 at 15 53 43" src="https://user-images.githubusercontent.com/107122512/216620420-d35ceb63-2e41-46ee-8fad-5a5f8e67b2ea.png">
