### DISCUSSION TITLE
Issue assigning variables as array elements

### DISCUSSION THREAD

**Discussion by KasparMinn** [buerokratt/Ruuter#166] [General]
Hi. A possible issue came up when trying to link variables as elements in an array of any type of object. For testing the issue, I have made two brief GET DSLs. 

```
assign_step:
  assign:
    year: 2024
    month: 12

print_step:
  assign:
    test_array:
      - thing_value:
          - code: Aasta
            selection:
              filter: item
              values:
                - "2029"
          - code: Paevitaja
            selection:
              filter: item
              values:
                - "12"
  next: return_step

return_step:
  return: ${test_array}

```

The above script returns a properly constructed JSON with correct array values. Here is the response:

```
{
    "response": [
        {
            "thing_value": [
                {
                    "code": "Aasta",
                    "selection": {
                        "filter": "item",
                        "values": [
                            2023
                        ]
                    }
                },
                {
                    "code": "Paevitaja",
                    "selection": {
                        "filter": "item",
                        "values": [
                            "2023"
                        ]
                    }
                }
            ]
        }
    ]
}
```

However, when trying to assign variables beforehand and then add them to the array, almost the entire response is wrapped in quotes. Here is a similar DSL where the issue comes up:

```
assign_step:
  assign:
    year: 2024
    month: 12

print_step:
  assign:
    test_array:
      - thing_value:
          - code: Aasta
            selection:
              filter: item
              values:
                - ${year}
          - code: Paevitaja
            selection:
              filter: item
              values:
                - ${month}
  next: return_step

return_step:
  return: ${test_array}
```

The above script returns a response wrapped in quotes:

```
{
    "response": "[{thing_value=[{code=Aasta, selection={filter=item, values=[2023]}}, {code=Paevitaja, selection={filter=item, values=[5]}}]}]"
}
```
