### ISSUE TITLE
Ruuter conditional switch

### ISSUE THREAD

**Issue by Kristjanmn** [buerokratt/Ruuter#126]
Problem description:

We are having an issue with following DSL:
```
checkForParam:
  switch:
    - condition: ${incoming.params.test == null} 
      next: returnNoParam
  next: returnParam
returnNoParam:
  return: "there was no test param ${incoming.params.test == null}"
  next: end
returnParam:
  return: "there was a test param ${incoming.params.test}"
  next: end
```

Problem is that DSL does not use correct next step when none of the switch conditions match.

By default `nextStepName` is `returnParam`.
When we call `http://localhost:8080/test-param?test=value` it goes to `returnParam`, which is correct.
When we call `http://localhost:8080/test-param` it goes to `returnNoParam`, which is also correct.
But when we call `http://localhost:8080/test-param?test=value` again it goes to `returnNoParam`, which is incorrect.

Source of the problem is that `DslStep` remembers previous `nextStepName` for that DSL and when none of the conditions in switch match, then instead of going past the switch and executing `returnParam` as next step, it instead executes `returnNoParam`, because it does not look past the switch.

Original message:

Can you help me understand this behaviour from Ruuter. Is there something extra we should be doing in our yaml or is this a bug with Ruuter when handling a conditional switch?
 
Given the following Ruuter endpoint, when you send a request with no params and then send another request with the required param, Ruuter will incorrectly handle the condition check

 

 

```
checkForParam:
  switch:
    - condition: ${incoming.params.test == null} 
      next: returnNoParam
  next: returnParam
returnNoParam:
  return: "there was no test param ${incoming.params.test == null}"
  next: end
returnParam:
  return: "there was a test param ${incoming.params.test}"
  next: end
```

 

Assuming the endpoint I copied is saved as GET/test-param.yml I have to make these requests:
 
```
curl --request GET 'http://localhost:8080/test-param?test=value'

 

curl --request GET 'http://localhost:8080/test-param'

 

curl --request GET 'http://localhost:8080/test-param?test=value'
```

 

Where the first 2 will have correct responses and the third will be incorrect

 

Is there any news on this issue? It seems to be pretty major, I'm also seeing requests randomly using the previous condition someone else triggered on the same endpoint. So for example if there are conditions A,B,C,D and someone made a request with condition A after which I made a request with condition B, Ruuter may also behave as if I had condition A, so the state of the condition seems to persist across requests at unpredictable times

    I just noticed this when working on the Overview page which has lots of metrics. I made all metrics refresh with a 1 second interval and numbers started jumping around, looking at the requests I can see that Ruuter is responding with results that belong to different requests at times

**Comment by Kristjanmn** [comment]
The issue is not present when you change `checkForParams` to
```
checkForParam:
  switch:
    - condition: ${incoming.params.test == null} 
      next: returnNoParam
    - condition: ${incoming.params.test != null} 
      next: returnParam
```
