### ISSUE TITLE
Pass variables in lists

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#160]
AS A Service Manager
I WANT TO pass variables in lists the same way it's done in all other cases
SO THAT I could make such REST requests where necessary

### Acceptance Criteria

- [ ] The following example DSL works

> Currently using `${currentYear.response.body.year}` as a variable doesn't work

#### Example DSL

```yml
currentYear:
  call: http.get
  args:
    url: https://www.timeapi.io/api/Time/current/zone?timeZone=Europe/Tallinn
  result: currentYear

correctYear:
  call: http.post
  args:
    url: https://andmed.stat.ee/api/v1/et/stat/RV021
    body:
      query:
        - code: Sugu
          selection:
            filter: item
            values:
              - 1
        - code: Aasta
          selection:
            filter: item
            values:
              - ${currentYear.response.body.year}
        - code: Vanuserühm
          selection:
            filter: item
            values:
              - 1
      response:
        format: json-stat2
  result: SAanswer
```
