### ISSUE TITLE
Ruuter GET request bugfix

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#170]
> This is a bugfix for #7 

### Acceptance Criteria

- [ ] #7 works according to https://github.com/buerokratt/Ruuter/blob/main/samples/steps/http-get.md
- [ ] If GET parameters exist in Ruuter DSL, the outgoing request is constructed based on them instead of matching `query string` parameters (if exist)

For example, in the following example, `queryVal` and `varFromDSL` are considered as DSL parameters to pass as GET query params:

```
get_message:
  call: http.get
  args:
    url: "[#DOMAIN_URL]:[#PORT]/scripting/passing-get-parameters"
    query:
      queryVal: queryVariableFromHell
      varFromDSL: "variableFromDSL"
```

**Comment by RayDNoper** [comment]
Used this DSL for testing:
```
get_message:
  call: http.get
  args:
    url: "http://localhost:9000/scripting/passing-get-parameters?url_param=value1"
    query:
      some_val: "Hello World"
      another_val: 123
  result: the_message
```
With netcat "simply-log-all-incoming-requests" ( `nc -k -l  -p 9000` ) running in localhost:9000.
This resulted with correctly formed GET request with all query parameters included and urlencoded:
```
GET /scripting/passing-get-parameters?url_param=value1&some_val=Hello%20World&another_val=123 HTTP/1.1
```
