### ISSUE TITLE
Sort the JavaScript array by its key values and return the minimum value within Ruuter DSL

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#184]
AS A Service Manager
I WANT TO sort the JavaScript array by its key values and return the minimum value within Ruuter DSL
SO THAT I could do it without using external components (for example, Data Mapper)

### Acceptance Criteria

- [ ] Example working DSL added

#### Expected DSL

> The example service is to fetch a list of electricity prices and output the lowest price

```yaml
get_step:
  call: http.get
  args:
    url: "https://dashboard.elering.ee/api/nps/price"    
  result: elering

response:
  return: ${elering.response.body.data.ee.sort( (a,b) =>  a.price-b.price )[0]}
```

#### Expected output

```json
{"response":{"timestamp":1687395600,"price":41.07}}
```
