### ISSUE TITLE
Add error handling to HTTP requests

### ISSUE THREAD

**Issue by RayDNoper** [buerokratt/Ruuter#198]
AS A Service Manager
I WANT TO specify the step to branch off to when HTTP request responds with non-OK
SO THAT that request can be modified programmatically or DSL to return information about situation

- [x] DSL step with HTTP non-OK response will step into specified DSL step

```yaml
get_message:
  call: http.get
  args:
    url: http://localhost:8080/guards/fail/mock-response #step that always gives 403
    query:
      var: "value"
  result: the_message
  error: error_step

return_value:
  return: ${the_message.request}
  
error_step:
  return: "Resource unavailable"
  status: 404
```
