### ISSUE TITLE
Use string concatenation

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#22]
AS A Service Manager
I WANT TO concatenate strings
SO THAT I could use them to describe rules, inputs and outputs within DSL-based services

Expected output: https://github.com/buerokratt/Ruuter/blob/main/samples/backlog/template-literals.md

```
- assign:
    var1: Büro
    var2: kratt
    var3: www.kratid ee

- return: ${var1 + var2 + " " + var3}
```
`Bürokratt www.kratid.ee`
