### ISSUE TITLE
Ruuter mixing up responses when multiple requests in parallel using conditions

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#256]
> [!IMPORTANT]
> In case of running multiple simultaneous threads on Ruuter, responses to requests get mixed up at some point

### Acceptance Criteria

- [ ] #325
- [ ] #326
- [ ] The linked discussion that is the base of this is issue can be closed due to being resolved

### Discussed in https://github.com/buerokratt/Ruuter/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **gdrui** February  3, 2023</sup>
Given an endpoint that fetches different data from Resql based on the provided parameters:
<details>

```
extract_request_data:
  assign:
    requestedMetric: ${incoming.params.metric}

checkMetric:
  switch:
    - condition: ${requestedMetric === 'total_chats_day'}
      next: getTotalChatsDayResults
    - condition: ${requestedMetric === 'total_chats_month'}
      next: getTotalChatsMonthResults
    - condition: ${requestedMetric === 'total_chats_no_csa_day'}
      next: getTotalChatsNoCSAResults
    - condition: ${requestedMetric === 'avg_chats_by_month'}
      next: getAvgChatsMonthResults
    - condition: ${requestedMetric === 'avg_chats_by_week'}
      next: getAvgChatsWeekResults
    - condition: ${requestedMetric === 'avg_chats_no_csa_by_month'}
      next: getAvgChatsNoCSAMonthResult
    - condition: ${requestedMetric === 'avg_chats_no_csa_by_week'}
      next: getAvgChatsNoCSAWeekResult
    - condition: ${requestedMetric === 'avg_waiting_time_day'}
      next: getAvgWaitingTimeDayResult
    - condition: ${requestedMetric === 'avg_waiting_time_week'}
      next: getAvgWaitingTimeWeekResult
    - condition: ${requestedMetric === 'total_forwarded_chats_yesterday'}
      next: getTotalForwardedChatsResult
    - condition: ${requestedMetric === 'chat-activity'}
      next: getChatActivityResult
  next: invalidMetric
```
</details>

If this endpoint is called once with any valid parameter it will return the correct result. 
However if many or all of these options are called in parallel requests then sometimes the results get mixed up and for example I can receive the result of `avg_waiting_time_day` when the request was with the parameter `total_chats_day`

I also tried to replace the individual steps so that instead of an asynchronous http.post step each step would only return a unique value like :
```
getTotalChatsDayResults:
  return: 'A'
  next: end
  
getTotalChatsMonthResults:
  return: 'B'
  next: end
...
```
This seems to happen less frequently like this, but I still observe the same thing happening:

When its OK:
<img width="498" alt="Screenshot 2023-02-03 at 11 21 18" src="https://user-images.githubusercontent.com/107122512/216561576-a8012ec7-1c12-474f-8735-f75bfefbbe6e.png">
When its not OK:
<img width="541" alt="Screenshot 2023-02-03 at 11 21 15" src="https://user-images.githubusercontent.com/107122512/216561695-23af8c42-4936-44ac-9a08-09ce7f500aa4.png">
</div>
