### ISSUE TITLE
Add Service Declaration to Ruuter DSLs

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#268]
AS AN Architect
I WANT Ruuter DSLs to have service declarations
SO THAT incoming request bodies could be validated against expectations

### Acceptance Criteria

- [ ] Every DSL may, but does not have to have a Service Declaration
- [ ] Log warnings if Service Declarations haven't been added
- [ ] Full documentation with sample Declarations

#### If Service Declaration exists

- [ ] Declare allowed request `body` parameters
- [ ] Declare allowed request `header` parameters
- [ ] Create OpenAPI spec based on Declaration
- [ ] Only the values defined in Declaration can be used within DSL
- [ ] If the same declared `body` parameters are sent more than once, stop processing the DSL
- [ ] If the same declared `header` parameters are sent more than once, stop processing the DSL

##### Full Declaration

```yaml
declaration:
  call: declare
  version: 0.1
  description: Test declara block functionality
  method: post
  accepts: json
  returns: json
  namespace:  backoffice
  allowlist:
    body:
      - field: input
        type: string
        description: Usual input field for declaration test
    headers:
      - field: Access-Control-Allow-Origin
        type: string
        description: Define allowed request origins
```

##### For OpenAPI spec only

```yaml
declaration:
  call: declare
  version: 0.1
  description: Test declara block functionality
  method: post
  accepts: json
  returns: json
  namespace:  backoffice
```

##### To declare allowed request parameters only

```yaml
declaration:
  call: declare
  allowlist:
    body:
      - field: input
        type: string
        description: Usual input field for declaration test
    headers:
      - field: Access-Control-Allow-Origin
        type: string
        description: Define allowed request origins
```
