### ISSUE TITLE
Define custom headers for incoming requests

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#5]
AS AN Architect
I WANT TO be able to define custom headers on global settings level based on actual headers and/or custom values
SO THAT I could meet specific architectural requirements where necessary

Expected output: https://github.com/buerokratt/Ruuter/blob/main/samples/backlog/settings/default.md
```
incoming_requests:
  headers:
    X-Forwarded-For: ${incoming.headers.remote_addr}
    X-Model-Type: application/vnd.classifier.classification+json;version=1
```
