### ISSUE TITLE
Redirect incoming message to an external endpoint

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#9]
AS AN Architect
I WANT TO be able to reflect all incoming messages to an external endpoint for validation
SO THAT I could implement _threat hunting_ etc related functionalities outside of Ruuter while still being able to stop Ruuter to further process the request if response code from that external endpoint is not within the values of Ruuter's `proceed_predicate`

#### Functionalities

> Added as additional functionalities since 20.06.2023

- [ ] #178

#### Initial development

Expected output: https://github.com/buerokratt/Ruuter/blob/main/samples/backlog/settings/default.md
```
incoming_requests:
  external_forwarding:
    method: POST
    endpoint: "https://turvis/ruuter-incoming"
    params_to_pass:
      GET: true
      POST: true
      headers: true
    proceed_predicate:
      http.status.code: [200..202]
```
